# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 651308b3ecca1af8abd91de19af9891c49b05edb823c1440adb16c2940d26fd43f7de7f6661394a5f355e88ea124c68dd3e4b114f957433d14ba7b665907eb82

test:
  secret_key_base: 5c6fc5a8f683bcb1c7a86a91886f487b60667d5b880a7136ec1a90932389ac101104ec519e2bd6cd951ce969ce951412c167ef12130cb579eb93f93f2056e8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
